added logic to docker command to run proxy in background

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,12 +36,13 @@ jobs:
       - run:  
           name: create proxy tunnel
           command: |
-            docker run --rm -it -p 8080:80 lindard/circle-sauce-node -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i builtbycircle
-            sleep 1
-            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
-            # while ! grep -m1 'Sauce Connect is up, you may start your tests.' < /tmp/sauce-connect-log.txt; do 
-            sleep 1
-            done
+            docker run --rm -it -p 8080:80 lindard/circle-sauce-node -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i builtbycircle --readyfile ~/sauce_is_ready:
+                background: true
+            # sleep 1
+            # wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
+            # while ! grep -m1 'Sauce Connect is up, you may start your tests.
+            # sleep 1
+            # done
             echo Sauce-Connect is up and running
             npm sauceLight
             kill $(cat pid)
